#if !defined(BSP_PINOUT_H_)
#define BSP_PINOUT_H_

#include "hal/gpio.h"
#include "hal/sercom_usart.h"

// TODO: isn't great that we include it, since it could transitively end up in the app
#include "sam.h"

/** AL8891 LED driver IC pins */
#define AL8891_ENABLE_PORT PORT_GROUP_A
#define AL8891_ENABLE_PIN 9

#define AL8891_FAULT_PORT PORT_GROUP_A
#define AL8891_FAULT_PIN 7
#define AL8891_FAULT_PINMUX MUX_PA07A_EIC_EXTINT7

#define AL8891_ADIM_PORT PORT_GROUP_A
#define AL8891_ADIM_PIN 2
#define AL8891_ADIM_PINMUX MUX_PA02B_DAC_VOUT

#define AL8891_PDIM_PORT PORT_GROUP_A
#define AL8891_PDIM_PIN 8

#define AL8891_MON_PORT PORT_GROUP_A
#define AL8891_MON_PIN 6
#define AL8891_MON_PINMUX MUX_PA06B_ADC_AIN6
#define AL8891_MON_ADC_INPUT ADC_INPUTCTRL_MUXPOS_PIN6_Val

/** Board NTC (Negative Temperature Coefficient) thermistor pins */
#define BOARD_NTC_PORT PORT_GROUP_A
#define BOARD_NTC_PIN 5
#define BOARD_NTC_PINMUX MUX_PA05B_ADC_AIN5
#define BOARD_NTC_ADC_INPUT ADC_INPUTCTRL_MUXPOS_PIN5_Val

/** Board VBUS sense pins */
#define BOARD_VBUS_SENSE_PORT PORT_GROUP_A
#define BOARD_VBUS_SENSE_PIN 11
#define BOARD_VBUS_SENSE_PINMUX MUX_PA11B_ADC_AIN19
#define BOARD_VBUS_SENSE_ADC_INPUT ADC_INPUTCTRL_MUXPOS_PIN19_Val

/** UART pins */
#define UART_SERCOM_INSTANCE SERCOM1

#define UART_CS_PORT PORT_GROUP_A
#define UART_CS_PIN 15

#define UART_TX_PORT PORT_GROUP_A
#define UART_TX_PIN 16
#define UART_TX_PINMUX MUX_PA16C_SERCOM1_PAD0

#define UART_RX_PORT PORT_GROUP_A
#define UART_RX_PIN 17
#define UART_RX_PINMUX MUX_PA17C_SERCOM1_PAD1

#define UART_TX_PAD SERCOM_USART_TX_PAD0
#define UART_RX_PAD SERCOM_USART_RX_PAD1

#define BOARD_BUTTON_PORT PORT_GROUP_A
#define BOARD_BUTTON_PIN 22
#define BOARD_BUTTON_PINMUX MUX_PA22A_EIC_EXTINT6

#endif // BSP_PINOUT_H_
